-- AlterTable
ALTER TABLE "Leads" ALTER COLUMN "name" DROP NOT NULL,
ALTER COLUMN "phone_number" DROP NOT NULL,
ALTER COLUMN "phone_id" DROP NOT NULL,
ALTER COLUMN "status" DROP NOT NULL,
ALTER COLUMN "disposition" DROP NOT NULL,
ALTER COLUMN "duration" DROP NOT NULL,
ALTER COLUMN "cost" DROP NOT NULL,
ALTER COLUMN "created_at" DROP NOT NULL,
ALTER COLUMN "recordingUrl" DROP NOT NULL,
ALTER COLUMN "initiated_at" DROP NOT NULL;
